# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', jsonfield.fields.JSONField(default=dict)),
                ('compare_value', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('finished', 'finished')], default='pending', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainCheck.Report'),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set([('report', 'name')]),
        ),
    ]
