# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('compare_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='domaincheck',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domainCheck.Feature'),
        ),
    ]
