# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domainCheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='domainCheck.Report'),
        ),
    ]
